# Goverment Data:

In this notebook , we will cover some basic data ingestion related to Goverment data.

In [2]:
import json
import os
import pandas as pd
import numpy as np
import requests

In [24]:
url = 'https://api.data.gov.in/resource/7b624b4a-1456-4945-80d0-dfb5e40ddcff?api-key=579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b&format=json&limit=800'

requestResponse = requests.get(url)
print(requestResponse.json())

{'index_name': '7b624b4a-1456-4945-80d0-dfb5e40ddcff', 'title': 'Monthly Consumption of Petroleum Products', 'desc': 'Monthly Consumption of Petroleum Products', 'created': 1685094503155, 'updated': 1775088055, 'created_date': '2023-05-26T15:18:55Z', 'updated_date': '2026-04-02T00:00:55Z', 'active': '1', 'visualizable': '1', 'catalog_uuid': 'd6d3a5a2-5c0d-4d79-9c66-baad771eb068', 'source': 'data.gov.in', 'org_type': 'Central', 'org': ['Ministry of Petroleum and Natural Gas', 'Petroleum Planning & Analysis Cell (PPAC)'], 'sector': ['Power and Energy'], 'field': [{'name': 'Month', 'id': '_month_', 'type': 'keyword'}, {'name': 'Year', 'id': 'year', 'type': 'double'}, {'name': 'PRODUCTS', 'id': 'products', 'type': 'keyword'}, {'name': 'Quantity (000 Metric Tonnes)', 'id': 'quantity_000_metric_tonnes_', 'type': 'double'}, {'name': 'updated_date', 'id': 'updated_date', 'type': 'date'}], 'target_bucket': {'index': 'api', 'type': 'd6d3a5a2-5c0d-4d79-9c66-baad771eb068', 'field': '7b624b4a-1456-4945-80d0-dfb5e40ddcff'}, 'message': 'Resource lists', 'version': '2.2.0', 'status': 'ok', 'total': 816, 'count': 10, 'limit': 10, 'offset': '0', 'records': [{'_month_': 'April', 'year': '2025', 'products': 'SKO', 'quantity_000_metric_tonnes_': '25.76', 'updated_date': '2026-04-01'}, {'_month_': 'April', 'year': '2025', 'products': 'LDO', 'quantity_000_metric_tonnes_': '85.54', 'updated_date': '2026-04-01'}, {'_month_': 'April', 'year': '2025', 'products': 'Petroleum coke', 'quantity_000_metric_tonnes_': '1544.69', 'updated_date': '2026-04-01'}, {'_month_': 'May', 'year': '2025', 'products': 'Bitumen', 'quantity_000_metric_tonnes_': '856.89', 'updated_date': '2026-04-01'}, {'_month_': 'May', 'year': '2025', 'products': 'Others', 'quantity_000_metric_tonnes_': '874.27', 'updated_date': '2026-04-01'}, {'_month_': 'June', 'year': '2025', 'products': 'LDO', 'quantity_000_metric_tonnes_': '86.36', 'updated_date': '2026-04-01'}, {'_month_': 'June', 'year': '2025', 'products': 'Lubricants & Greases', 'quantity_000_metric_tonnes_': '392.62', 'updated_date': '2026-04-01'}, {'_month_': 'June', 'year': '2025', 'products': 'FO & LSHS', 'quantity_000_metric_tonnes_': '497.63', 'updated_date': '2026-04-01'}, {'_month_': 'June', 'year': '2025', 'products': 'Bitumen', 'quantity_000_metric_tonnes_': '698.89', 'updated_date': '2026-04-01'}, {'_month_': 'July', 'year': '2025', 'products': 'Lubricants & Greases', 'quantity_000_metric_tonnes_': '393.21', 'updated_date': '2026-04-01'}]}

In [27]:
df = pd.json_normalize(requestResponse.json(),record_path=['records'], meta=['records'])
df.head(150)

,_month_,year,products,quantity_000_metric_tonnes_,updated_date,records
0,April,2025,SKO,25.76,2026-04-01,"[{'_month_': 'April', 'year': '2025', 'product..."
1,April,2025,LDO,85.54,2026-04-01,"[{'_month_': 'April', 'year': '2025', 'product..."
2,April,2025,Petroleum coke,1544.69,2026-04-01,"[{'_month_': 'April', 'year': '2025', 'product..."
3,May,2025,Bitumen,856.89,2026-04-01,"[{'_month_': 'April', 'year': '2025', 'product..."
4,May,2025,Others,874.27,2026-04-01,"[{'_month_': 'April', 'year': '2025', 'product..."
5,June,2025,LDO,86.36,2026-04-01,"[{'_month_': 'April', 'year': '2025', 'product..."
6,June,2025,Lubricants & Greases,392.62,2026-04-01,"[{'_month_': 'April', 'year': '2025', 'product..."
7,June,2025,FO & LSHS,497.63,2026-04-01,"[{'_month_': 'April', 'year': '2025', 'product..."
8,June,2025,Bitumen,698.89,2026-04-01,"[{'_month_': 'April', 'year': '2025', 'product..."
9,July,2025,Lubricants & Greases,393.21,2026-04-01,"[{'_month_': 'April', 'year': '2025', 'product..."

In [26]:
df.count()

_month_                        10
year                           10
products                       10
quantity_000_metric_tonnes_    10
updated_date                   10
records                        10
dtype: int64

In [29]:
url = 'https://api.data.gov.in/resource/06c9065f-70eb-4cb8-a0c0-e560291cf7f5?api-key=579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b&format=json&limit=20'
requestResponse = requests.get(url)
df = pd.json_normalize(requestResponse.json(),record_path=['records'], meta=['records'])
df.head(150)

,category,sub__groups___products,__2015_16,__2016_17,_2017_18,_2018_19,_2019_20,_2020_21,_2021_22,_2022_23,_2023_24,_2024_25,records
0,Alkali Chemicals,Soda Ash,2583013,2613419,2989570,3048187,3069431,2638117,3078901,3219315,2975782,3279271,"[{'category': 'Alkali Chemicals', 'sub__groups..."
1,Alkali Chemicals,Caustic Soda,2503955,2594495,2742313,2925352,3136937,2964078,3462771,3604471,3617989,3926649,"[{'category': 'Alkali Chemicals', 'sub__groups..."
2,Alkali Chemicals,Liquid Chlorine,1714816,1800666,1899412,2069111,2250429,2174264,2499329,2668849,2640410,2731796,"[{'category': 'Alkali Chemicals', 'sub__groups..."
3,Total - Alkali Chemicals,Total,6801784,7008580,7631295,8042650,8456797,7776459,9041001,9492635,9234181,9937716,"[{'category': 'Alkali Chemicals', 'sub__groups..."
4,Inorganic Chemicals,Aluminium Fluoride,9514,8142,7514,5697,5050,3698,8909,5307,5384,5203,"[{'category': 'Alkali Chemicals', 'sub__groups..."
5,Inorganic Chemicals,Calcium Carbide,83472,85021,87297,83170,81339,86778,98618,83437,80129,86176,"[{'category': 'Alkali Chemicals', 'sub__groups..."
6,Inorganic Chemicals,Carbon Black,469561,535273,530356,546390,500146,384780,456487,447003,484376,548498,"[{'category': 'Alkali Chemicals', 'sub__groups..."
7,Inorganic Chemicals,Potassium Chlorate,406,12,347,703,16178,17079,17678,14233,17090,17778,"[{'category': 'Alkali Chemicals', 'sub__groups..."
8,Inorganic Chemicals,Sodium Chlorate,0,0,0,NA,NA,17917,21144,23210,21485,21468,"[{'category': 'Alkali Chemicals', 'sub__groups..."
9,Inorganic Chemicals,Titanium Dioxide,58533,58459,57817,57059,49487,51222,56957,46811,54015,52344,"[{'category': 'Alkali Chemicals', 'sub__groups..."